import Link from "next/link"
import { Package, Star, CheckCircle2, Sparkles } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { cn, getCategoryEmoji } from "@/lib/utils"

type ListCardProps = {
  list: {
    id: string
    name: string
    category: string | null
    category_emoji: string
    ai_comment: string | null
    ai_title_edited: boolean
    productCount: number
    shortlistedCount: number
    purchasedCount: number
    memberCount: number
  }
}

function getStatusBadge(shortlisted: number, purchased: number) {
  if (purchased > 0)
    return { label: "Purchased", className: "bg-purchased/20 text-purchased border-purchased/30" }
  if (shortlisted > 0)
    return { label: "Deciding", className: "bg-shortlisted/20 text-shortlisted border-shortlisted/30" }
  return { label: "Researching", className: "" }
}

export function ListCard({ list }: ListCardProps) {
  // Use AI-generated emoji if available, fall back to deterministic mapping
  const emoji = list.category_emoji !== "📋"
    ? list.category_emoji
    : getCategoryEmoji(list.category)
  const status = getStatusBadge(list.shortlistedCount, list.purchasedCount)

  return (
    <Link href={`/lists/${list.id}`} className="block group">
      <Card className="h-full transition-all duration-150 hover:shadow-lg group-hover:-translate-y-0.5 cursor-pointer">
        <CardContent className="p-5 space-y-3">
          {/* Emoji + Title */}
          <div className="space-y-1">
            <span className="text-2xl">{emoji}</span>
            <h3 className="font-semibold text-lg leading-tight line-clamp-2">
              {!list.ai_title_edited && (
                <Sparkles className="inline h-4 w-4 mr-1 text-ai-accent" />
              )}
              {list.name}
            </h3>
          </div>

          {/* Stats row */}
          <div className="flex items-center gap-3 text-sm text-muted-foreground">
            <span className="flex items-center gap-1">
              <Package className="h-3.5 w-3.5" />
              {list.productCount}
            </span>
            {list.shortlistedCount > 0 && (
              <span className="flex items-center gap-1">
                <Star className="h-3.5 w-3.5" />
                {list.shortlistedCount}
              </span>
            )}
            {list.purchasedCount > 0 && (
              <span className="flex items-center gap-1">
                <CheckCircle2 className="h-3.5 w-3.5" />
                {list.purchasedCount}
              </span>
            )}
          </div>

          {/* AI comment bubble */}
          {list.ai_comment && (
            <p
              className="text-sm text-muted-foreground italic bg-muted/50 rounded-lg px-3 py-2 border-l-2 border-ai-accent/30 line-clamp-2"
              aria-label={`AI comment: ${list.ai_comment}`}
              aria-description="Generated by AI"
            >
              <span className="text-xs mr-1">🤖</span>
              {list.ai_comment}
            </p>
          )}

          {/* Bottom row: status + member count */}
          <div className="flex items-center justify-between">
            <Badge
              variant="secondary"
              className={cn("text-xs", status.className)}
            >
              {status.label}
            </Badge>
            <span className="text-xs text-muted-foreground">
              {list.memberCount} {list.memberCount === 1 ? "member" : "members"}
            </span>
          </div>
        </CardContent>
      </Card>
    </Link>
  )
}
